apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: jithupauljacob-com-tls
spec:
  secretName: jithupauljacob-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: jithupauljacob.com
  dnsNames:
    - jithupauljacob.com
    - www.jithupauljacob.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - jithupauljacob.com
          - www.jithupauljacob.com  
